package com.philipcosgrave.calorietracker.ui

enum class AppScreen {
    Home,
    Scan,
    Insights,
    More,
    Diary,
    Weight,
    LogWeight,
    SearchFood,
    SyncSettings,
    QuickCalories,
    AddIngredient,
    RecipeBuilder,
    LogFood,
    FoodDetails,
    BarcodeScanner,
    PhotoFood,
    VoiceReview,
    SpeakFood,
    ManageFoods,
    Leftovers,
    CopyMeals,
    AddedFood,
    FoodCreated,
}
