import type { CatalogItem } from "./types";

export const hiddenSeedStorageKey = "calorie-tracker:hidden-seed-options:v1";

export const catalogItems: CatalogItem[] = [
  {
    id: "ingredient-coffee",
    kind: "ingredient",
    name: "Coffee",
    servingLabel: "16 oz",
    servingQuantity: 16,
    servingUnit: "oz",
    nutrients: { calories: 9, proteinGrams: 0.5, carbohydrateGrams: 0, fatGrams: 0 },
    frequency: 18,
    lastUsedDaysAgo: 0,
  },
  {
    id: "ingredient-greek-yogurt",
    kind: "ingredient",
    name: "Greek yogurt",
    brand: "Plain",
    barcode: "012345678905",
    servingLabel: "1 cup",
    servingQuantity: 1,
    servingUnit: "cup",
    servingGrams: 227,
    nutrients: { calories: 140, proteinGrams: 20, carbohydrateGrams: 8, fatGrams: 3 },
    frequency: 14,
    lastUsedDaysAgo: 1,
  },
  {
    id: "ingredient-banana",
    kind: "ingredient",
    name: "Banana",
    servingLabel: "1 medium",
    servingQuantity: 1,
    servingUnit: "banana",
    servingGrams: 118,
    nutrients: { calories: 105, proteinGrams: 1.3, carbohydrateGrams: 27, fatGrams: 0.4 },
    frequency: 10,
    lastUsedDaysAgo: 2,
  },
  {
    id: "ingredient-oats",
    kind: "ingredient",
    name: "Rolled oats",
    servingLabel: "1/2 cup",
    servingQuantity: 0.5,
    servingUnit: "cup",
    servingGrams: 40,
    nutrients: { calories: 150, proteinGrams: 5, carbohydrateGrams: 27, fatGrams: 3 },
    frequency: 7,
    lastUsedDaysAgo: 4,
  },
  {
    id: "recipe-yogurt-bowl",
    kind: "recipe",
    name: "Yogurt banana bowl",
    servingLabel: "1 bowl",
    servingQuantity: 1,
    servingUnit: "bowl",
    nutrients: { calories: 395, proteinGrams: 26, carbohydrateGrams: 62, fatGrams: 6.4 },
    ingredients: ["Greek yogurt - 1 cup", "Banana - 1 medium", "Rolled oats - 1/2 cup"],
    frequency: 8,
    lastUsedDaysAgo: 1,
  },
  {
    id: "recipe-breakfast-wrap",
    kind: "recipe",
    name: "Breakfast egg wrap",
    servingLabel: "1 wrap",
    servingQuantity: 1,
    servingUnit: "wrap",
    nutrients: { calories: 430, proteinGrams: 25, carbohydrateGrams: 38, fatGrams: 19 },
    ingredients: ["Eggs - 2 eggs", "Tortilla - 1 wrap", "Cheddar - 1 oz", "Spinach - 1 cup"],
    frequency: 5,
    lastUsedDaysAgo: 6,
  },
];
