name: Deploy Backend Dev

on:
  workflow_dispatch:
  push:
    branches:
      - dev

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    uses: ./.github/workflows/_deploy-backend-and-infra.yml
    with:
      github_environment: dev
      terraform_environment: dev
    secrets: inherit
